[build-system]
requires = ["setuptools>=65.5", "wheel>=0.45"]
build-backend = "setuptools.build_meta"

[project]
name = "pytalises"
version = "0.2.7"
description = "TALISES (This Ain't a LInear Schrödinger Equation Solver) is an easy-to-use Python implementation of the Split-Step Fourier Method for time-propagation under the Schrödinger equation."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
  { name = "Sascha Vowe", email = "sascha.vowe@posteo.de" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Physics",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "numpy>=1.19",
  "scipy>=1.5",
  "numba>=0.50",
  "pyfftw>=0.12",
  "numexpr>=2.7",
]

[project.urls]
Homepage = "http://github.com/savowe/pytalises"
Repository = "http://github.com/savowe/pytalises"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
include = ["pytalises"]
